# *************************************
# * Parameters for metemirge pipeline *
# *************************************

# List of files
list_files: "/home/aschick/projects/test_metemirge/list_files.txt"

# EMIRGE parameters
input_dir: "/home/aschick/projects/test_metemirge/data/fastq/"
fasta_db: "/home/aschick/refs/silva/SILVA_132_SSURef_Nr99_tax_silva_trunc.ge1200bp.le2000bp.0.97.fixed.fasta"
bowtie_db: "/home/aschick/refs/silva/SILVA_132_SSURef_Nr99_tax_silva_trunc.ge1200bp.le2000bp.0.97.fixed"
max_read_length: 100
insert_mean: 240
insert_stddev: 100
num_iter: 5
num_iter_str: "05" # If this is <10, add a 0 before the number to make it two digits

# BLAST parameters
path_to_blastdbs: "/home/aschick/refs/blast/"
list_blastdb_names: ["16SMicrobial", "ure_16s"]
evalue: 1e-05
max_target_seqs: 10





# Any other parameters
